# Generated by Django 3.0.7 on 2020-06-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidheadlines',
            name='source',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
