# Generated by Django 3.0.7 on 2020-06-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidData', '0003_covidclinicaltrials'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidheadlines',
            name='publishedData',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
