# Generated by Django 3.0.7 on 2020-07-22 01:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidData', '0004_covidheadlines_publisheddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='covidTreatmentTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatmentTypes', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', null=True), default=list, size=None), size=None)),
            ],
        ),
    ]
