# Generated by Django 3.0.7 on 2020-07-27 17:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidData', '0006_auto_20200727_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidtreatmenttypes',
            name='treatmentTypes',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', null=True), default=list, size=None), size=None),
        ),
    ]
