# Generated by Django 3.0.7 on 2020-07-28 15:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='covidClinicalTrials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('briefSummary', models.TextField(blank=True, null=True)),
                ('detailedDesc', models.TextField(blank=True, null=True)),
                ('studyType', models.CharField(max_length=200)),
                ('studyPhase', models.CharField(max_length=200)),
                ('firstintervention', models.CharField(max_length=200)),
                ('secondintervention', models.CharField(max_length=200)),
                ('enrollment', models.CharField(max_length=200)),
                ('startDate', models.CharField(max_length=200)),
                ('primaryCompletionDate', models.CharField(max_length=200)),
                ('studyCompletionDate', models.CharField(max_length=200)),
                ('armfirstintervention', models.CharField(max_length=200)),
                ('armSecondintervention', models.CharField(max_length=200)),
                ('primaryOutcomeMes', models.TextField(blank=True, null=True)),
                ('secondaryOutcomeMes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='covidHeadlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('url', models.TextField()),
                ('desc', models.TextField(blank=True, null=True)),
                ('publishedData', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='covidTreatmentTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatmentTypes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', null=True), default=list, size=None)),
                ('treatmentTypeFreq', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', null=True), default=list, size=None)),
            ],
        ),
    ]
