from django import forms

from .models import currencies

currency_choice = [
    ('AFN', 'AFN - Afghani'),
    ('ALL', 'ALL - Lek'),
    ('DZD', 'DZD - Algerian Dinar'),
    ('USD', 'USD - US Dollar'),
    ('EUR', 'EUR - Euro'),
    ('AOA', 'AOA - Kwanza'),
    ('XCD', 'XCD - East Caribbean Dollar'),
    ('', ' - No universal currency'),
    ('ARS', 'ARS - Argentine Peso'),
    ('AMD', 'AMD - Armenian Dram'),
    ('AWG', 'AWG - Aruban Florin'),
    ('AUD', 'AUD - Australian Dollar'),
    ('AZN', 'AZN - Azerbaijanian Manat'),
    ('BSD', 'BSD - Bahamian Dollar'),
    ('BHD', 'BHD - Bahraini Dinar'),
    ('BDT', 'BDT - Taka'),
    ('BBD', 'BBD - Barbados Dollar'),
    ('BYN', 'BYN - Belarussian Ruble'),
    ('BZD', 'BZD - Belize Dollar'),
    ('XOF', 'XOF - CFA Franc BCEAO'),
    ('BMD', 'BMD - Bermudian Dollar'),
    ('BTN', 'BTN - Ngultrum'),
    ('INR', 'INR - Indian Rupee'),
    ('BOB', 'BOB - Boliviano'),
    ('BOV', 'BOV - Mvdol'),
    ('BAM', 'BAM - Convertible Mark'),
    ('BWP', 'BWP - Pula'),
    ('NOK', 'NOK - Norwegian Krone'),
    ('BRL', 'BRL - Brazilian Real'),
    ('BND', 'BND - Brunei Dollar'),
    ('BGN', 'BGN - Bulgarian Lev'),
    ('BIF', 'BIF - Burundi Franc'),
    ('CVE', 'CVE - Cabo Verde Escudo'),
    ('KHR', 'KHR - Riel'),
    ('XAF', 'XAF - CFA Franc BEAC'),
    ('CAD', 'CAD - Canadian Dollar'),
    ('KYD', 'KYD - Cayman Islands Dollar'),
    ('CLF', 'CLF - Unidad de Fomento'),
    ('CLP', 'CLP - Chilean Peso'),
    ('CNY', 'CNY - Yuan Renminbi'),
    ('COP', 'COP - Colombian Peso'),
    ('COU', 'COU - Unidad de Valor Real'),
    ('KMF', 'KMF - Comoro Franc'),
    ('CDF', 'CDF - Congolese Franc'),
    ('NZD', 'NZD - New Zealand Dollar'),
    ('CRC', 'CRC - Costa Rican Colon'),
    ('HRK', 'HRK - Kuna'),
    ('CUC', 'CUC - Peso Convertible'),
    ('CUP', 'CUP - Cuban Peso'),
    ('ANG', 'ANG - Netherlands Antillean Guilder'),
    ('CZK', 'CZK - Czech Koruna'),
    ('DKK', 'DKK - Danish Krone'),
    ('DJF', 'DJF - Djibouti Franc'),
    ('DOP', 'DOP - Dominican Peso'),
    ('EGP', 'EGP - Egyptian Pound'),
    ('SVC', 'SVC - El Salvador Colon'),
    ('ERN', 'ERN - Nakfa'),
    ('ETB', 'ETB - Ethiopian Birr'),
    ('FKP', 'FKP - Falkland Islands Pound'),
    ('FJD', 'FJD - Fiji Dollar'),
    ('XPF', 'XPF - CFP Franc'),
    ('GMD', 'GMD - Dalasi'),
    ('GEL', 'GEL - Lari'),
    ('GHS', 'GHS - Ghana Cedi'),
    ('GIP', 'GIP - Gibraltar Pound'),
    ('GTQ', 'GTQ - Quetzal'),
    ('GBP', 'GBP - Pound Sterling'),
    ('GNF', 'GNF - Guinea Franc'),
    ('GYD', 'GYD - Guyana Dollar'),
    ('HTG', 'HTG - Gourde'),
    ('HNL', 'HNL - Lempira'),
    ('HKD', 'HKD - Hong Kong Dollar'),
    ('HUF', 'HUF - Forint'),
    ('ISK', 'ISK - Iceland Krona'),
    ('IDR', 'IDR - Rupiah'),
    ('XDR', 'XDR - SDR (Special Drawing Right)'),
    ('IRR', 'IRR - Iranian Rial'),
    ('IQD', 'IQD - Iraqi Dinar'),
    ('ILS', 'ILS - New Israeli Sheqel'),
    ('JMD', 'JMD - Jamaican Dollar'),
    ('JPY', 'JPY - Yen'),
    ('JOD', 'JOD - Jordanian Dinar'),
    ('KZT', 'KZT - Tenge'),
    ('KES', 'KES - Kenyan Shilling'),
    ('KPW', 'KPW - North Korean Won'),
    ('KRW', 'KRW - Won'),
    ('KWD', 'KWD - Kuwaiti Dinar'),
    ('KGS', 'KGS - Som'),
    ('LAK', 'LAK - Kip'),
    ('LBP', 'LBP - Lebanese Pound'),
    ('LSL', 'LSL - Loti'),
    ('ZAR', 'ZAR - Rand'),
    ('LRD', 'LRD - Liberian Dollar'),
    ('LYD', 'LYD - Libyan Dinar'),
    ('CHF', 'CHF - Swiss Franc'),
    ('MOP', 'MOP - Pataca'),
    ('MGA', 'MGA - Malagasy Ariary'),
    ('MWK', 'MWK - Kwacha'),
    ('MYR', 'MYR - Malaysian Ringgit'),
    ('MVR', 'MVR - Rufiyaa'),
    ('MRU', 'MRU - Ouguiya'),
    ('MUR', 'MUR - Mauritius Rupee'),
    ('XUA', 'XUA - ADB Unit of Account'),
    ('MXN', 'MXN - Mexican Peso'),
    ('MXV', 'MXV - Mexican Unidad de Inversion (UDI)'),
    ('MDL', 'MDL - Moldovan Leu'),
    ('MNT', 'MNT - Tugrik'),
    ('MAD', 'MAD - Moroccan Dirham'),
    ('MZN', 'MZN - Mozambique Metical'),
    ('MMK', 'MMK - Kyat'),
    ('NAD', 'NAD - Namibia Dollar'),
    ('NPR', 'NPR - Nepalese Rupee'),
    ('NIO', 'NIO - Cordoba Oro'),
    ('NGN', 'NGN - Naira'),
    ('OMR', 'OMR - Rial Omani'),
    ('PKR', 'PKR - Pakistan Rupee'),
    ('PAB', 'PAB - Balboa'),
    ('PGK', 'PGK - Kina'),
    ('PYG', 'PYG - Guarani'),
    ('PEN', 'PEN - Nuevo Sol'),
    ('PHP', 'PHP - Philippine Peso'),
    ('PLN', 'PLN - Zloty'),
    ('QAR', 'QAR - Qatari Rial'),
    ('MKD', 'MKD - Denar'),
    ('RON', 'RON - Romanian Leu'),
    ('RUB', 'RUB - Russian Ruble'),
    ('RWF', 'RWF - Rwanda Franc'),
    ('SHP', 'SHP - Saint Helena Pound'),
    ('WST', 'WST - Tala'),
    ('STN', 'STN - Dobra'),
    ('SAR', 'SAR - Saudi Riyal'),
    ('RSD', 'RSD - Serbian Dinar'),
    ('SCR', 'SCR - Seychelles Rupee'),
    ('SLL', 'SLL - Leone'),
    ('SGD', 'SGD - Singapore Dollar'),
    ('XSU', 'XSU - Sucre'),
    ('SBD', 'SBD - Solomon Islands Dollar'),
    ('SOS', 'SOS - Somali Shilling'),
    ('SSP', 'SSP - South Sudanese Pound'),
    ('LKR', 'LKR - Sri Lanka Rupee'),
    ('SDG', 'SDG - Sudanese Pound'),
    ('SRD', 'SRD - Surinam Dollar'),
    ('SZL', 'SZL - Lilangeni'),
    ('SEK', 'SEK - Swedish Krona'),
    ('CHE', 'CHE - WIR Euro'),
    ('CHW', 'CHW - WIR Franc'),
    ('SYP', 'SYP - Syrian Pound'),
    ('TWD', 'TWD - New Taiwan Dollar'),
    ('TJS', 'TJS - Somoni'),
    ('TZS', 'TZS - Tanzanian Shilling'),
    ('THB', 'THB - Baht'),
    ('TOP', 'TOP - Pa’anga'),
    ('TTD', 'TTD - Trinidad and Tobago Dollar'),
    ('TND', 'TND - Tunisian Dinar'),
    ('TRY', 'TRY - Turkish Lira'),
    ('TMT', 'TMT - Turkmenistan New Manat'),
    ('UGX', 'UGX - Uganda Shilling'),
    ('UAH', 'UAH - Hryvnia'),
    ('AED', 'AED - UAE Dirham'),
    ('USN', 'USN - US Dollar (Next day)'),
    ('UYI', 'UYI - Uruguay Peso'),
    ('UYU', 'UYU - Peso Uruguayo'),
    ('UZS', 'UZS - Uzbekistan Sum'),
    ('VUV', 'VUV - Vatu'),
    ('VEF', 'VEF - Bolivar'),
    ('VND', 'VND - Dong'),
    ('YER', 'YER - Yemeni Rial'),
    ('ZMW', 'ZMW - Zambian Kwacha'),
    ('ZWL', 'ZWL - Zimbabwe Dollar'),
]


class currencyForm(forms.ModelForm):
    firstCurrencyChoice = forms.CharField(widget=forms.Select(choices=currency_choice))
    secondCurrencyChoice = forms.CharField(widget=forms.Select(choices=currency_choice))
    
    class Meta:
        model = currencies
        fields = {
            'firstCurrencyChoice',
            'secondCurrencyChoice',
        }